---

- hosts: "{{ hosts | default('nowhere') }}"
  serial: 1
  pre_tasks:
      - name: De-register {{ ansible_default_ipv4.address }} from lb
        when: aliyun_lb_weight is defined
        local_action:
            module: aliyun_lb
            instance_id: "{{ aliyun_instance_id }}"
            lb_id: "{{ aliyun_lb_id }}"
            region: cn-hangzhou
            weight: "{{ aliyun_lb_weight }}"
            wait: True
            wait_timeout: 60
            state: absent

  roles:
      - role: maas

  post_tasks:
      - name: Register {{ ansible_default_ipv4.address }} to lb
        when: aliyun_lb_weight is defined
        local_action:
            module: aliyun_lb
            instance_id: "{{ aliyun_instance_id }}"
            lb_id: "{{ aliyun_lb_id }}"
            region: cn-hangzhou
            weight: "{{ aliyun_lb_weight }}"
            wait: True
            wait_timeout: 180
            state: present
