/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro.LookupEventMessage;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AuthenticationInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7096731594293579191L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AuthenticationInfo\",\"namespace\":\"com.ecreditpal.maas.common.avro.LookupEventMessage\",\"fields\":[{\"name\":\"is_authenticated\",\"type\":\"boolean\",\"default\":false},{\"name\":\"failure_message\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public boolean is_authenticated;
  @Deprecated public java.lang.CharSequence failure_message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AuthenticationInfo() {}

  /**
   * All-args constructor.
   * @param is_authenticated The new value for is_authenticated
   * @param failure_message The new value for failure_message
   */
  public AuthenticationInfo(java.lang.Boolean is_authenticated, java.lang.CharSequence failure_message) {
    this.is_authenticated = is_authenticated;
    this.failure_message = failure_message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return is_authenticated;
    case 1: return failure_message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: is_authenticated = (java.lang.Boolean)value$; break;
    case 1: failure_message = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'is_authenticated' field.
   * @return The value of the 'is_authenticated' field.
   */
  public java.lang.Boolean getIsAuthenticated() {
    return is_authenticated;
  }

  /**
   * Sets the value of the 'is_authenticated' field.
   * @param value the value to set.
   */
  public void setIsAuthenticated(java.lang.Boolean value) {
    this.is_authenticated = value;
  }

  /**
   * Gets the value of the 'failure_message' field.
   * @return The value of the 'failure_message' field.
   */
  public java.lang.CharSequence getFailureMessage() {
    return failure_message;
  }

  /**
   * Sets the value of the 'failure_message' field.
   * @param value the value to set.
   */
  public void setFailureMessage(java.lang.CharSequence value) {
    this.failure_message = value;
  }

  /**
   * Creates a new AuthenticationInfo RecordBuilder.
   * @return A new AuthenticationInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder newBuilder() {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder();
  }

  /**
   * Creates a new AuthenticationInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AuthenticationInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder(other);
  }

  /**
   * Creates a new AuthenticationInfo RecordBuilder by copying an existing AuthenticationInfo instance.
   * @param other The existing instance to copy.
   * @return A new AuthenticationInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder(other);
  }

  /**
   * RecordBuilder for AuthenticationInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AuthenticationInfo>
    implements org.apache.avro.data.RecordBuilder<AuthenticationInfo> {

    private boolean is_authenticated;
    private java.lang.CharSequence failure_message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.is_authenticated)) {
        this.is_authenticated = data().deepCopy(fields()[0].schema(), other.is_authenticated);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.failure_message)) {
        this.failure_message = data().deepCopy(fields()[1].schema(), other.failure_message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AuthenticationInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.is_authenticated)) {
        this.is_authenticated = data().deepCopy(fields()[0].schema(), other.is_authenticated);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.failure_message)) {
        this.failure_message = data().deepCopy(fields()[1].schema(), other.failure_message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'is_authenticated' field.
      * @return The value.
      */
    public java.lang.Boolean getIsAuthenticated() {
      return is_authenticated;
    }

    /**
      * Sets the value of the 'is_authenticated' field.
      * @param value The value of 'is_authenticated'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder setIsAuthenticated(boolean value) {
      validate(fields()[0], value);
      this.is_authenticated = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'is_authenticated' field has been set.
      * @return True if the 'is_authenticated' field has been set, false otherwise.
      */
    public boolean hasIsAuthenticated() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'is_authenticated' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder clearIsAuthenticated() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'failure_message' field.
      * @return The value.
      */
    public java.lang.CharSequence getFailureMessage() {
      return failure_message;
    }

    /**
      * Sets the value of the 'failure_message' field.
      * @param value The value of 'failure_message'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder setFailureMessage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.failure_message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'failure_message' field has been set.
      * @return True if the 'failure_message' field has been set, false otherwise.
      */
    public boolean hasFailureMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'failure_message' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.AuthenticationInfo.Builder clearFailureMessage() {
      failure_message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AuthenticationInfo build() {
      try {
        AuthenticationInfo record = new AuthenticationInfo();
        record.is_authenticated = fieldSetFlags()[0] ? this.is_authenticated : (java.lang.Boolean) defaultValue(fields()[0]);
        record.failure_message = fieldSetFlags()[1] ? this.failure_message : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
