/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro.LookupEventMessage;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ResponseInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5356341319910031060L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResponseInfo\",\"namespace\":\"com.ecreditpal.maas.common.avro.LookupEventMessage\",\"fields\":[{\"name\":\"response_code\",\"type\":\"int\",\"default\":200},{\"name\":\"response_body\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int response_code;
  @Deprecated public java.lang.CharSequence response_body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResponseInfo() {}

  /**
   * All-args constructor.
   * @param response_code The new value for response_code
   * @param response_body The new value for response_body
   */
  public ResponseInfo(java.lang.Integer response_code, java.lang.CharSequence response_body) {
    this.response_code = response_code;
    this.response_body = response_body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return response_code;
    case 1: return response_body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: response_code = (java.lang.Integer)value$; break;
    case 1: response_body = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'response_code' field.
   * @return The value of the 'response_code' field.
   */
  public java.lang.Integer getResponseCode() {
    return response_code;
  }

  /**
   * Sets the value of the 'response_code' field.
   * @param value the value to set.
   */
  public void setResponseCode(java.lang.Integer value) {
    this.response_code = value;
  }

  /**
   * Gets the value of the 'response_body' field.
   * @return The value of the 'response_body' field.
   */
  public java.lang.CharSequence getResponseBody() {
    return response_body;
  }

  /**
   * Sets the value of the 'response_body' field.
   * @param value the value to set.
   */
  public void setResponseBody(java.lang.CharSequence value) {
    this.response_body = value;
  }

  /**
   * Creates a new ResponseInfo RecordBuilder.
   * @return A new ResponseInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder newBuilder() {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder();
  }

  /**
   * Creates a new ResponseInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResponseInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder(other);
  }

  /**
   * Creates a new ResponseInfo RecordBuilder by copying an existing ResponseInfo instance.
   * @param other The existing instance to copy.
   * @return A new ResponseInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder(other);
  }

  /**
   * RecordBuilder for ResponseInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResponseInfo>
    implements org.apache.avro.data.RecordBuilder<ResponseInfo> {

    private int response_code;
    private java.lang.CharSequence response_body;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.response_code)) {
        this.response_code = data().deepCopy(fields()[0].schema(), other.response_code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.response_body)) {
        this.response_body = data().deepCopy(fields()[1].schema(), other.response_body);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ResponseInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.response_code)) {
        this.response_code = data().deepCopy(fields()[0].schema(), other.response_code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.response_body)) {
        this.response_body = data().deepCopy(fields()[1].schema(), other.response_body);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'response_code' field.
      * @return The value.
      */
    public java.lang.Integer getResponseCode() {
      return response_code;
    }

    /**
      * Sets the value of the 'response_code' field.
      * @param value The value of 'response_code'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder setResponseCode(int value) {
      validate(fields()[0], value);
      this.response_code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'response_code' field has been set.
      * @return True if the 'response_code' field has been set, false otherwise.
      */
    public boolean hasResponseCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'response_code' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder clearResponseCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'response_body' field.
      * @return The value.
      */
    public java.lang.CharSequence getResponseBody() {
      return response_body;
    }

    /**
      * Sets the value of the 'response_body' field.
      * @param value The value of 'response_body'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder setResponseBody(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.response_body = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'response_body' field has been set.
      * @return True if the 'response_body' field has been set, false otherwise.
      */
    public boolean hasResponseBody() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'response_body' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.ResponseInfo.Builder clearResponseBody() {
      response_body = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ResponseInfo build() {
      try {
        ResponseInfo record = new ResponseInfo();
        record.response_code = fieldSetFlags()[0] ? this.response_code : (java.lang.Integer) defaultValue(fields()[0]);
        record.response_body = fieldSetFlags()[1] ? this.response_body : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
