/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro.LookupEventMessage;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8716569964769441927L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserInfo\",\"namespace\":\"com.ecreditpal.maas.common.avro.LookupEventMessage\",\"fields\":[{\"name\":\"user_id\",\"type\":\"long\",\"default\":-1},{\"name\":\"user_name\",\"type\":\"string\",\"default\":\"ANONYMOUS\"},{\"name\":\"allowed_apis\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"whitelisted_ips\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long user_id;
  @Deprecated public java.lang.CharSequence user_name;
  @Deprecated public java.util.List<java.lang.CharSequence> allowed_apis;
  @Deprecated public java.util.List<java.lang.CharSequence> whitelisted_ips;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserInfo() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param user_name The new value for user_name
   * @param allowed_apis The new value for allowed_apis
   * @param whitelisted_ips The new value for whitelisted_ips
   */
  public UserInfo(java.lang.Long user_id, java.lang.CharSequence user_name, java.util.List<java.lang.CharSequence> allowed_apis, java.util.List<java.lang.CharSequence> whitelisted_ips) {
    this.user_id = user_id;
    this.user_name = user_name;
    this.allowed_apis = allowed_apis;
    this.whitelisted_ips = whitelisted_ips;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return user_name;
    case 2: return allowed_apis;
    case 3: return whitelisted_ips;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.Long)value$; break;
    case 1: user_name = (java.lang.CharSequence)value$; break;
    case 2: allowed_apis = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: whitelisted_ips = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.Long getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'user_name' field.
   * @return The value of the 'user_name' field.
   */
  public java.lang.CharSequence getUserName() {
    return user_name;
  }

  /**
   * Sets the value of the 'user_name' field.
   * @param value the value to set.
   */
  public void setUserName(java.lang.CharSequence value) {
    this.user_name = value;
  }

  /**
   * Gets the value of the 'allowed_apis' field.
   * @return The value of the 'allowed_apis' field.
   */
  public java.util.List<java.lang.CharSequence> getAllowedApis() {
    return allowed_apis;
  }

  /**
   * Sets the value of the 'allowed_apis' field.
   * @param value the value to set.
   */
  public void setAllowedApis(java.util.List<java.lang.CharSequence> value) {
    this.allowed_apis = value;
  }

  /**
   * Gets the value of the 'whitelisted_ips' field.
   * @return The value of the 'whitelisted_ips' field.
   */
  public java.util.List<java.lang.CharSequence> getWhitelistedIps() {
    return whitelisted_ips;
  }

  /**
   * Sets the value of the 'whitelisted_ips' field.
   * @param value the value to set.
   */
  public void setWhitelistedIps(java.util.List<java.lang.CharSequence> value) {
    this.whitelisted_ips = value;
  }

  /**
   * Creates a new UserInfo RecordBuilder.
   * @return A new UserInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder newBuilder() {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder();
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder(other);
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing UserInfo instance.
   * @param other The existing instance to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder(other);
  }

  /**
   * RecordBuilder for UserInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserInfo>
    implements org.apache.avro.data.RecordBuilder<UserInfo> {

    private long user_id;
    private java.lang.CharSequence user_name;
    private java.util.List<java.lang.CharSequence> allowed_apis;
    private java.util.List<java.lang.CharSequence> whitelisted_ips;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.user_name)) {
        this.user_name = data().deepCopy(fields()[1].schema(), other.user_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.allowed_apis)) {
        this.allowed_apis = data().deepCopy(fields()[2].schema(), other.allowed_apis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.whitelisted_ips)) {
        this.whitelisted_ips = data().deepCopy(fields()[3].schema(), other.whitelisted_ips);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.user_name)) {
        this.user_name = data().deepCopy(fields()[1].schema(), other.user_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.allowed_apis)) {
        this.allowed_apis = data().deepCopy(fields()[2].schema(), other.allowed_apis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.whitelisted_ips)) {
        this.whitelisted_ips = data().deepCopy(fields()[3].schema(), other.whitelisted_ips);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return user_id;
    }

    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserName() {
      return user_name;
    }

    /**
      * Sets the value of the 'user_name' field.
      * @param value The value of 'user_name'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder setUserName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.user_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'user_name' field has been set.
      * @return True if the 'user_name' field has been set, false otherwise.
      */
    public boolean hasUserName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'user_name' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder clearUserName() {
      user_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'allowed_apis' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getAllowedApis() {
      return allowed_apis;
    }

    /**
      * Sets the value of the 'allowed_apis' field.
      * @param value The value of 'allowed_apis'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder setAllowedApis(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.allowed_apis = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'allowed_apis' field has been set.
      * @return True if the 'allowed_apis' field has been set, false otherwise.
      */
    public boolean hasAllowedApis() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'allowed_apis' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder clearAllowedApis() {
      allowed_apis = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'whitelisted_ips' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getWhitelistedIps() {
      return whitelisted_ips;
    }

    /**
      * Sets the value of the 'whitelisted_ips' field.
      * @param value The value of 'whitelisted_ips'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder setWhitelistedIps(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.whitelisted_ips = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'whitelisted_ips' field has been set.
      * @return True if the 'whitelisted_ips' field has been set, false otherwise.
      */
    public boolean hasWhitelistedIps() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'whitelisted_ips' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.UserInfo.Builder clearWhitelistedIps() {
      whitelisted_ips = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public UserInfo build() {
      try {
        UserInfo record = new UserInfo();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.Long) defaultValue(fields()[0]);
        record.user_name = fieldSetFlags()[1] ? this.user_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.allowed_apis = fieldSetFlags()[2] ? this.allowed_apis : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.whitelisted_ips = fieldSetFlags()[3] ? this.whitelisted_ips : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
