/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro.LookupEventMessage;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class VariableResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7509215495900967384L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VariableResult\",\"namespace\":\"com.ecreditpal.maas.common.avro.LookupEventMessage\",\"fields\":[{\"name\":\"variable_name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"variable_value\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence variable_name;
  @Deprecated public java.lang.CharSequence variable_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VariableResult() {}

  /**
   * All-args constructor.
   * @param variable_name The new value for variable_name
   * @param variable_value The new value for variable_value
   */
  public VariableResult(java.lang.CharSequence variable_name, java.lang.CharSequence variable_value) {
    this.variable_name = variable_name;
    this.variable_value = variable_value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variable_name;
    case 1: return variable_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variable_name = (java.lang.CharSequence)value$; break;
    case 1: variable_value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'variable_name' field.
   * @return The value of the 'variable_name' field.
   */
  public java.lang.CharSequence getVariableName() {
    return variable_name;
  }

  /**
   * Sets the value of the 'variable_name' field.
   * @param value the value to set.
   */
  public void setVariableName(java.lang.CharSequence value) {
    this.variable_name = value;
  }

  /**
   * Gets the value of the 'variable_value' field.
   * @return The value of the 'variable_value' field.
   */
  public java.lang.CharSequence getVariableValue() {
    return variable_value;
  }

  /**
   * Sets the value of the 'variable_value' field.
   * @param value the value to set.
   */
  public void setVariableValue(java.lang.CharSequence value) {
    this.variable_value = value;
  }

  /**
   * Creates a new VariableResult RecordBuilder.
   * @return A new VariableResult RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder newBuilder() {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder();
  }

  /**
   * Creates a new VariableResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VariableResult RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder(other);
  }

  /**
   * Creates a new VariableResult RecordBuilder by copying an existing VariableResult instance.
   * @param other The existing instance to copy.
   * @return A new VariableResult RecordBuilder
   */
  public static com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder newBuilder(com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult other) {
    return new com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder(other);
  }

  /**
   * RecordBuilder for VariableResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VariableResult>
    implements org.apache.avro.data.RecordBuilder<VariableResult> {

    private java.lang.CharSequence variable_name;
    private java.lang.CharSequence variable_value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.variable_name)) {
        this.variable_name = data().deepCopy(fields()[0].schema(), other.variable_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.variable_value)) {
        this.variable_value = data().deepCopy(fields()[1].schema(), other.variable_value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing VariableResult instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.variable_name)) {
        this.variable_name = data().deepCopy(fields()[0].schema(), other.variable_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.variable_value)) {
        this.variable_value = data().deepCopy(fields()[1].schema(), other.variable_value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'variable_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getVariableName() {
      return variable_name;
    }

    /**
      * Sets the value of the 'variable_name' field.
      * @param value The value of 'variable_name'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder setVariableName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.variable_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'variable_name' field has been set.
      * @return True if the 'variable_name' field has been set, false otherwise.
      */
    public boolean hasVariableName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'variable_name' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder clearVariableName() {
      variable_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'variable_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getVariableValue() {
      return variable_value;
    }

    /**
      * Sets the value of the 'variable_value' field.
      * @param value The value of 'variable_value'.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder setVariableValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.variable_value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'variable_value' field has been set.
      * @return True if the 'variable_value' field has been set, false otherwise.
      */
    public boolean hasVariableValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'variable_value' field.
      * @return This builder.
      */
    public com.ecreditpal.maas.common.avro.LookupEventMessage.VariableResult.Builder clearVariableValue() {
      variable_value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public VariableResult build() {
      try {
        VariableResult record = new VariableResult();
        record.variable_name = fieldSetFlags()[0] ? this.variable_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.variable_value = fieldSetFlags()[1] ? this.variable_value : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
