/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum dataSourceType {
  UNIONPAY, P2P  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"dataSourceType\",\"namespace\":\"com.ecreditpal.maas.common.avro\",\"symbols\":[\"UNIONPAY\",\"P2P\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
