/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecreditpal.maas.common.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum loanStatusType {
  UNKNOWN, DUE, DUE_THEN_CLEARED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"loanStatusType\",\"namespace\":\"com.ecreditpal.maas.common.avro\",\"symbols\":[\"UNKNOWN\",\"DUE\",\"DUE_THEN_CLEARED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
